### ISSUE TITLE
RemoveX not working as expected?

### ISSUE THREAD

**Issue by jeffsilva** [vattle/sqlboiler#97]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
2.1.7

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler postgres

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
table customer(id primary key, name)
table address(id primary key, street_name)
table customer_address(customer_id, address_id)

Yes singular table names... don't ask... :)

### Further information. What did you do, what did you expect?

    boil.DebugMode = true
    customer.RemoveAddressesG(address)
    address.DeleteG()

I was trying to remove an address from a customer with  RemoveAddressesG and it did not work.
Looking at the debug output i could tell that boiler is not passing the address id to the query:
```
customer.RemoveAddressesG(address)
delete from "customer_address" where "customer_id" = $1 and "address_id" in ($1)  <== (notice the $1 used twice)
[122] <== no address_id only the customer_id
address.DeleteG()
DELETE FROM "address" WHERE "id"=$1
7 <== the address_id is being passed to address.DeleteG()
```

The call to address.DeleteG() fails because customer_address still references it
Heres is the generated customer.RemoveAddressesG code (also notice the struct name, Addres)
It calls RemoveAddresses:
```go
func (o *Customer) RemoveAddresses(exec boil.Executor, related ...*Addres) error {
	var err error
	query := fmt.Sprintf(
		"delete from \"customer_address\" where \"customer_id\" = $1 and \"address_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, len(related), 1, 1),
	)
	values := []interface{}{o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeAddressesFromCustomersSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Addresses {
			if rel != ri {
				continue
			}

			ln := len(o.R.Addresses)
			if ln > 1 && i < ln-1 {
				o.R.Addresses[i] = o.R.Addresses[ln-1]
			}
			o.R.Addresses = o.R.Addresses[:ln-1]
			break
		}
	}

	return nil
}
```
To work around this, for now i am adding the items from the related slice to the value slice which is not being done by boiler and changing the 3rd argument to strmangle.Placeholders to 2

then the debug output was correct and it worked as expected:

    delete from "customer_address" where "customer_id" = $1 and "address_id" in ($2)
    [122 7]

Sorry if i am actually doing something wrong, i am new to sqlboiler, thanks!

**Comment by aarondl** [comment]
Hey @jeffsilva. I've pushed a fix for the messed up parameter to the dev branch. Also, we very recently fixed an issue with Address being turned into Addres and that lives in the dev branch as well. Could you perhaps try that branch and see if that fixes it?

**Comment by jeffsilva** [comment]
Hi @aarondl, you are still not appending the "related"s id into the value slice

```go
values := []interface{}{o.ID}
// maybe like this?
for _, r := range related {
    value = append(value, r.id)
}
```

**Comment by aarondl** [comment]
Sorry, I did have a little bit of trouble figuring out what the initial bug report was about with the slice bit. Turns out some tests had been disabled and so I had no idea we were having these kinds of failures. I re-enabled the tests and fixed the breakages in the dev branch. Please let me know if it works for you now :)

**Comment by jeffsilva** [comment]
> Sorry, I did have a little bit of trouble figuring out what the initial bug report was about with the slice bit. 

My bad i guess, i will try to be clearer in the future.
> Turns out some tests had been disabled and so I had no idea we were having these kinds of failures. I 
re-enabled...

Yeah i was surprised that all tests passed. Good to know there were tests covering this and that they are enabled again.

The dev branch solves both this and the naming issue, thanks.
